config=~/github/NixOS-Journey
HISTFILE=~/.zsh_history
bindkey -v
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=true
MODE_INDICATOR="🟢" # 普通模式
INSERT_MODE_INDICATOR="🔴" # 插入模式
RPROMPT="\$(vi_mode_prompt_info)$RPROMPT"
